// ============================================
// EASTER EGG CHARACTERS (CANON, IMMUTABLE)
// ============================================
const easterEggPlayersData = {
    1: {
        name: "Oh Il-nam",
        personality: {
            age: 77,
            gender: "Male",
            country: "South Korea",
            occupation: "Retired",
            debt: 0,
        },
        stats: {
            strength: 1,
            agility: 1,
            intelligence: 15,
            charisma: 10,
            luck: 10,
            cowardice: 2,
            greed: 10,
        },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/2/29/Oh-ll-nam_2020.png/revision/latest/scale-to-width/360?cb=20250126120528",
    },
    7: {
        name: "Park Yong-sik",
        personality: {
            age: 39,
            gender: "Male",
            country: "South Korea",
            occupation: "Unemployed",
            debt: 210000,
        },
        stats: { strength: 5, agility: 4, intelligence: 5, charisma: 2, luck: 5, cowardice: 11, greed: 3 },
        photoURL: "https://i.redd.it/here-is-what-i-think-will-happen-to-player-007-yong-sik-and-v0-km4tveirmyre1.jpg?width=1079&format=pjpg&auto=webp&s=c50bbe2a5061a08a287363c2ea8ea67d37e0144e",
    },
    44: {
        name: "Seon-Nyeo",
        personality: {
            age: 49,
            gender: "Female",
            country: "South Korea",
            occupation: "Shaman",
            debt: 100000,
        },
        stats: { strength: 4, agility: 5, intelligence: 8, charisma: 15, luck: 10, cowardice: 6, greed: 10 },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/b/bd/Player044_N.jpg/revision/latest/scale-to-width-down/1200?cb=20250630194513",
    },
    67: {
        name: "Kang Sae-byeok",
        personality: {
            age: 23,
            gender: "Female",
            country: "North Korea",
            occupation: "Defector",
            debt: 40000,
        },
        stats: { strength: 5, agility: 7, intelligence: 9, charisma: 1, luck: 6, cowardice: 2, greed: 5 },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/f/f4/Kang_Sae-byeok.png/revision/latest?cb=20250916115418",
    },
    95: {
        name: "Young-Mi",
        personality: {
            age: 25,
            gender: "Female",
            country: "South Korea",
            occupation: "Unemployed",
            debt: 25000,
        },
        stats: { strength: 2, agility: 7, intelligence: 5, charisma: 3, luck: 3, cowardice: 8, greed: 1 },
        photoURL: "https://s.yimg.com/ny/api/res/1.2/Q65_OCPdL6TAYMYKJbLJjw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyNDI7aD02OTk7Y2Y9d2VicA--/https://media.zenfs.com/en/mandatory_995/2f5b7e255575ae8da68b2ecf38f55f23",
    },
    100: {
        name: "Im Jeong-dae",
        personality: {
            age: 29,
            gender: "Male",
            country: "South Korea",
            occupation: "Businessman",
            debt: 10000000,
        },
        stats: { strength: 3, agility: 3, intelligence: 8, charisma: 15, luck: 8, cowardice: 8, greed: 13 },
        photoURL: "https://preview.redd.it/unpopular-opinion-i-think-player-100-was-one-of-the-v0-ieux3msf8ehf1.jpeg?auto=webp&s=6ce6586ac7aab1729a1d7ffe1d8f66f6b3fad4c3",
    },
    101: {
        name: "Jang Deok-su",
        personality: {
            age: 44,
            gender: "Male",
            country: "South Korea",
            occupation: "Gangster",
            debt: 1200000,
        },
        stats: { strength: 11, agility: 6, intelligence: 5, charisma: 8, luck: 6, cowardice: 2, greed: 10 },
        photoURL: "https://64.media.tumblr.com/800b77c51be892235c9ae3de67816d7e/95093e286c64ebfb-21/s540x810/15e869f7e9766a7068ee446efd2e0a7a96af7b73.gif",
    },
    111: {
        name: "Byeon-gi",
        personality: {
            age: 44,
            gender: "Male",
            country: "South Korea",
            occupation: "Doctor",
            debt: 1100000,
        },
        stats: { strength: 8, agility: 8, intelligence: 8, charisma: 8, luck: 6, cowardice: 3, greed: 10 },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/6/6f/Byeong-gi.png/revision/latest?cb=20240216074508",
    },
    120: {
        name: "Cho Hyun-Ju",
        personality: {
            age: 38,
            gender: "Male",
            country: "South Korea",
            occupation: "Former Marine",
            debt: 330000,
        },
        stats: { strength: 10, agility: 10, intelligence: 10, charisma: 6, luck: 5, cowardice: 0, greed: 3 },
        photoURL: "https://i.pinimg.com/236x/0a/c9/ae/0ac9ae623a2f70a0b61c613c4637fc78.jpg",
    },
    124: {
        name: "Nam-su",
        personality: {
            age: 31,
            gender: "Male",
            country: "South Korea",
            occupation: "Security Guard",
            debt: 150000,
        },
        stats: { strength: 6, agility: 6, intelligence: 5, charisma: 3, luck: 5, cowardice: 1, greed: 10 },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/d/df/Player124_n.jpg/revision/latest/thumbnail/width/360/height/450?cb=20250211122522",
    },
    125: {
        name: "Park Min-su",
        personality: {
            age: 25,
            gender: "Male",
            country: "South Korea",
            occupation: "Office Worker",
            debt: 65000,
        },
        stats: { strength: 3, agility: 8, intelligence: 5, charisma: 1, luck: 8, cowardice: 11, greed: 1 },
        photoURL: "https://i.pinimg.com/236x/68/47/4b/68474b21217a95102808aec76ffd6757.jpg",
    },
    132: {
        name: "Young-Il",
        personality: {
            age: 35,
            gender: "Male",
            country: "South Korea",
            occupation: "Investor",
            debt: 0,
        },
        stats: { strength: 10, agility: 10, intelligence: 15, charisma: 10, luck: 10, cowardice: 0, greed: 10 },
        photoURL: "https://preview.redd.it/who-is-player-001-in-the-first-game-of-season-2-v0-rvhu1y3wb1ie1.jpeg?width=350&auto=webp&s=29a2aced0cd30e8fffbcb5ebbc0ffc2979d05da6",
    },
    149: {
        name: "Jang Geum-Ja",
        personality: {
            age: 70,
            gender: "Female",
            country: "South Korea",
            occupation: "Midwife",
            debt: 0,
        },
        stats: { strength: 2, agility: 5, intelligence: 7, charisma: 5, luck: 9, cowardice: 2, greed: 0 },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/5/52/JangGeum-ja.png/revision/latest?cb=20250103030318",
    },
    196: {
        name: "Kang Mi-Na",
        personality: {
            age: 27,
            gender: "Female",
            country: "South Korea",
            occupation: "Influencer",
            debt: 45000,
        },
        stats: { strength: 3, agility: 6, intelligence: 2, charisma: 6, luck: 1, cowardice: 8, greed: 2 },
    },
    199: {
        name: "Ali Abdul",
        personality: {
            age: 33,
            gender: "Male",
            country: "Pakistan",
            occupation: "Factory Worker",
            debt: 5000,
        },
        stats: { strength: 10, agility: 7, intelligence: 6, charisma: 9, luck: 4, cowardice: 5, greed: 1 },
        photoURL: "https://upload.wikimedia.org/wikipedia/en/thumb/b/bd/Ali_Abdul_Squid_Game.jpg/250px-Ali_Abdul_Squid_Game.jpg",
    },
    203: {
        name: "Kim Gi-min",
        personality: {
            age: 46,
            gender: "Male",
            country: "South Korea",
            occupation: "Bartender",
            debt: 300000,
        },
        stats: { strength: 8, agility: 8, intelligence: 7, charisma: 6, luck: 6, cowardice: 1, greed: 10 },
    },
    212: {
        name: "Han Mi-nyeo",
        personality: {
            age: 46,
            gender: "Female",
            country: "South Korea",
            occupation: "Fraudster",
            debt: 200000,
        },
        stats: { strength: 4, agility: 8, intelligence: 6, charisma: 9, luck: 9, cowardice: 2, greed: 7 },
        photoURL: "https://upload.wikimedia.org/wikipedia/en/2/2a/Han_Mi-nyeo.png",
    },
    218: {
        name: "Cho Sang-woo",
        personality: {
            age: 46,
            gender: "Male",
            country: "South Korea",
            occupation: "Head of Securities",
            debt: 4700000,
        },
        stats: { strength: 6, agility: 6, intelligence: 11, charisma: 3, luck: 8, cowardice: 2, greed: 11 },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/8/8f/Sang-woo_during_red_light_green_light.jpg/revision/latest/scale-to-width-down/736?cb=20250105033101",
    },
    222: {
        name: "Kim Jun-hee",
        personality: {
            age: 28,
            gender: "Female",
            country: "South Korea",
            occupation: "Unemployed",
            debt: 100000,
        },
        stats: { strength: 3, agility: 5, intelligence: 5, charisma: 4, luck: 5, cowardice: 6, greed: 1 },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/c/c5/Player222.jpg/revision/latest/scale-to-width-down/250?cb=20241110155810",
    },
    226: {
        name: "Kim Yeong-Sam",
        personality: {
            age: 46,
            gender: "Male",
            country: "South Korea",
            occupation: "Employed",
            debt: 1900000,
        },
        stats: { strength: 6, agility: 8, intelligence: 7, charisma: 9, luck: 5, cowardice: 2, greed: 10 },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/5/5a/KimYeong-sam1.png/revision/latest?cb=20241229032549",
    },
    230: {
        name: "Thanos",
        personality: {
            age: 24,
            gender: "Male",
            country: "Unknown",
            occupation: "Rapper",
            debt: 75000,
        },
        stats: { strength: 5, agility: 6, intelligence: 7, charisma: 9, luck: 6, cowardice: 4, greed: 8 },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/8/88/Thanos_Player_Picture.jpg/revision/latest/thumbnail/width/360/height/450?cb=20250528110557",
    },
    246: {
        name: "Park Gyeong-seok",
        personality: {
            age: 44,
            gender: "Male",
            country: "South Korea",
            occupation: "Artist",
            debt: 100000,
        },
        stats: { strength: 7, agility: 7, intelligence: 7, charisma: 3, luck: 10, cowardice: 3, greed: 0 },
    },
    333: {
        name: "Lee Myung-gi",
        personality: {
            age: 49,
            gender: "Male",
            country: "South Korea",
            occupation: "YouTuber",
            debt: 800000,
        },
        stats: { strength: 7, agility: 7, intelligence: 9, charisma: 1, luck: 7, cowardice: 0, greed: 10 },
        photoURL: "https://cdn.polyspeak.ai/speakmaster/9e6636f6fee739075903b5196b8bd7ae.webp",
    },
    337: {
        name: "MemeTemple",
        personality: {
            age: 23,
            gender: "Male",
            country: "Unknown",
            occupation: "Plumber",
            debt: 1300,
        },
        stats: { strength: 7, agility: 9, intelligence: 7, charisma: 6, luck: 5, cowardice: 3, greed: 1 },
    },
    380: {
        name: "Han Se-Mi",
        personality: {
            age: 25,
            gender: "Female",
            country: "South Korea",
            occupation: "Makeup Artist",
            debt: 200000,
        },
        stats: { strength: 4, agility: 8, intelligence: 6, charisma: 7, luck: 3, cowardice: 2, greed: 5 },
        photoURL: "https://preview.redd.it/opinions-on-380-v0-h0zkrchy899e1.jpeg?auto=webp&s=1fc0904560bbd8156edbe7346884cab0a26e4f56",
    },
    388: {
        name: "Kang Dae-Ho",
        personality: {
            age: 34,
            gender: "Male",
            country: "South Korea",
            occupation: "Unemployed",
            debt: 45000,
        },
        stats: { strength: 6, agility: 7, intelligence: 5, charisma: 6, luck: 5, cowardice: 10, greed: 3 },
        photoURL: "https://static.wikia.nocookie.net/thesquidgame/images/d/d3/DaeHo388.png/revision/latest/scale-to-width-down/250?cb=20250705181447",
    },
    390: {
        name: "Park Jung-bae",
        personality: {
            age: 41,
            gender: "Male",
            country: "South Korea",
            occupation: "Small Business Owner",
            debt: 110000,
        },
        stats: { strength: 6, agility: 6, intelligence: 8, charisma: 9, luck: 6, cowardice: 1, greed: 2 },
        photoURL: "https://shapes.inc/api/public/avatar/parkjungbae",
    },
    456: {
        name: "Seong Gi-hun",
        personality: {
            age: 47,
            gender: "Male",
            country: "South Korea",
            occupation: "Chauffeur",
            debt: 340000,
        },
        stats: { strength: 7, agility: 8, intelligence: 6, charisma: 7, luck: 15, cowardice: 1, greed: 1 },
        photoURL: "https://upload.wikimedia.org/wikipedia/en/c/c1/Seong_Gi-hun_season_1.png",
    },
};

// Manual Easter Egg map (same IDs as easterEggPlayersData, can be extended)
const manualEasterEggData = { ...easterEggPlayersData };
